### ISSUE TITLE
remove useless code

### ISSUE THREAD

**Issue by MariMax** [NikaOrl/next-datepicker#25]
module should work without providers and imports
<img width="631" alt="Screen Shot 2019-03-08 at 2 55 53 PM" src="https://user-images.githubusercontent.com/3389677/54052411-57879c00-41b2-11e9-8e72-38684d61befc.png">

**Comment by NikaOrl** [comment]
The component doesn't build without imports: [FormsModule, NgbDatepickerModule],
The rest import and providers have been removed
