### ISSUE TITLE
input should have active styles while datepicker is open

### ISSUE THREAD

**Issue by MariMax** [NikaOrl/next-datepicker#31]
can check nibr-bootstrap.css

**Comment by NikaOrl** [comment]
@MariMax But nibr-bootstrap.css has no :active styles for an input. Should I add some styles for input:active in the component scss or nibr-bootstrap.css or where? Or should I just make input :active while datepicker is open?

**Comment by MariMax** [comment]
it definitely has :focus, I'd add class to input when datepicker open and set the same styles

**Comment by NikaOrl** [comment]
@MariMax and I should add styles to this class in nibr-bootstrap.css that is added only in the storybook? Or should I add it into the component like @extend .form-control:focus (There are problems course styles for  .form-control:focus are adding after it but I would try to do my best if it's necessary)

**Comment by MariMax** [comment]
similar to .form-control:focus in the component
